WITH USING_CAR AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)
SELECT DISTINCT C.CAR_ID,
    CASE
        WHEN U.CAR_ID IS NOT NULL THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
LEFT JOIN USING_CAR U ON C.CAR_ID = U.CAR_ID
ORDER BY C.CAR_ID DESC;