(
    SELECT NAME RESULTS
    FROM MOVIERATING M LEFT JOIN USERS U ON M.USER_ID = U.USER_ID
    GROUP BY M.USER_ID
    ORDER BY COUNT(M.USER_ID) DESC, U.NAME ASC
    LIMIT 1
)
UNION ALL
(
    SELECT TITLE RESULTS
    FROM MOVIERATING R LEFT JOIN MOVIES M ON M.MOVIE_ID = R.MOVIE_ID
    WHERE CREATED_AT BETWEEN '2020-02-01' AND '2020-02-29'
    GROUP BY R.MOVIE_ID
    ORDER BY AVG(RATING) DESC, TITLE ASC
    LIMIT 1
);