SELECT R.APNT_NO, P.PT_NAME, R.PT_NO, R.MCDP_CD, D.DR_NAME, R.APNT_YMD
FROM (
    SELECT *
    FROM APPOINTMENT
    WHERE MCDP_CD = 'CS' AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND APNT_CNCL_YN = 'N'
    ) R, DOCTOR D, PATIENT P
WHERE R.PT_NO = P.PT_NO AND R.MDDR_ID = D.DR_ID
ORDER BY 6;