-- 재귀함수
-- WITH RECURSIVE CTE AS (초기조건 UNION ALL 반복조건)

WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT P.ID, P.PARENT_ID, C.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA P
    INNER JOIN CTE C ON P.PARENT_ID = C.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI_DATA RIGHT JOIN CTE ON ECOLI_DATA.PARENT_ID = CTE.ID
WHERE ECOLI_DATA.ID IS NULL
GROUP BY 2
ORDER BY 2;