WITH CODES AS (SELECT
    (SELECT CODE FROM SKILLCODES WHERE NAME = 'PYTHON') PY_CODE
    , (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') C_CODE
    , (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'FRONT END') FE_CODE
    FROM DUAL)
SELECT CASE 
    WHEN (SKILL_CODE & FE_CODE) AND (SKILL_CODE & PY_CODE) THEN 'A'
    WHEN SKILL_CODE & C_CODE THEN 'B'
    WHEN SKILL_CODE & FE_CODE THEN 'C'
END GRADE, ID, EMAIL
FROM DEVELOPERS, CODES
WHERE SKILL_CODE & (FE_CODE+C_CODE)
ORDER BY GRADE, ID;