WITH MAX_FISH AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT M.ID, N.FISH_NAME, M.LENGTH
FROM (
         SELECT FISH_INFO.ID, MAX_FISH.FISH_TYPE, MAX_FISH.LENGTH
         FROM MAX_FISH
                  LEFT JOIN FISH_INFO ON MAX_FISH.FISH_TYPE = FISH_INFO.FISH_TYPE
         WHERE MAX_FISH.LENGTH = FISH_INFO.LENGTH
     ) M
         LEFT JOIN FISH_NAME_INFO N ON M.FISH_TYPE = N.FISH_TYPE
ORDER BY M.ID;