WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT E.ID, E.PARENT_ID, CTE.GEN + 1
    FROM ECOLI_DATA E
    JOIN CTE ON CTE.ID = E.PARENT_ID
)

SELECT COUNT(A.ID) AS COUNT, A.GEN AS GENERATION
FROM CTE A
LEFT JOIN CTE B ON A.ID = B.PARENT_ID
WHERE B.ID IS NULL
GROUP BY A.GEN
ORDER BY A.GEN;
