WITH TOTAL_SCORES AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
),
MAX_SCORE AS (
    SELECT MAX(SCORE) AS MAX_SCORE
    FROM TOTAL_SCORES
),
BEST_EMPLOYEE AS (
    SELECT TS.EMP_NO, TS.SCORE
    FROM TOTAL_SCORES TS
    JOIN MAX_SCORE M
    ON TS.SCORE = M.MAX_SCORE
)
SELECT BE.SCORE AS SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES HE
RIGHT JOIN BEST_EMPLOYEE BE
ON HE.EMP_NO = BE.EMP_NO;