WITH INFO AS (
    SELECT *
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
)
SELECT UGU.USER_ID, UGU.NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
        CONCAT(SUBSTRING(UGU.TLNO , 1, 3), '-', 
               SUBSTRING(UGU.TLNO , 4, 4), '-',
               SUBSTRING(UGU.TLNO , 8, 4)
              ) AS 전화번호
FROM INFO
JOIN USED_GOODS_USER AS UGU
ON INFO.WRITER_ID = UGU.USER_ID
ORDER BY USER_ID DESC;