SELECT CAR_ID, ROUND(SUM(DATEDIFF(END_DATE, DATE_SUB(START_DATE, INTERVAL 1 DAY))) / COUNT(*), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;