WITH FISH_MAX AS (
    SELECT *
    FROM (
        SELECT *, 
               ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RN
        FROM FISH_INFO
    ) ranked
    WHERE RN = 1
)
SELECT ID, FISH_NAME, LENGTH
FROM FISH_MAX
LEFT JOIN FISH_NAME_INFO
ON FISH_MAX.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
ORDER BY ID;