SELECT HE.EMP_NO, HE.EMP_NAME,
    CASE
        WHEN AHG.AVG_SCORE >= 96 THEN 'S'
        WHEN AHG.AVG_SCORE >= 90 THEN 'A'
        WHEN AHG.AVG_SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE, 
    CASE
        WHEN AHG.AVG_SCORE >= 96 THEN HE.SAL * 0.2
        WHEN AHG.AVG_SCORE >= 90 THEN HE.SAL * 0.15
        WHEN AHG.AVG_SCORE >= 80 THEN HE.SAL * 0.10
    ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES HE
LEFT JOIN 
    (
        SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
    )   AS AHG
ON HE.EMP_NO = AHG.EMP_NO
ORDER BY HE.EMP_NO;