-- 2022년 3월의 오프라인/온라인
-- 판매 날짜, 상품id, 유저id, 판매량
-- offline_dale의 user_id null로
-- 판매일 기준 오름차순, 상품id 오름, 유저id 오름

WITH ON_AND_OFF AS (
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
UNION ALL
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3)

SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ON_AND_OFF
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;