SELECT AP.APNT_NO, PT.PT_NAME, AP.PT_NO, AP.MCDP_CD, DR.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AP
LEFT JOIN PATIENT PT ON AP.PT_NO = PT.PT_NO
LEFT JOIN DOCTOR DR ON AP.MDDR_ID = DR.DR_ID
WHERE DATE_FORMAT(AP.APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND AP.APNT_CNCL_YN = 'N'
ORDER BY AP.APNT_YMD;