SELECT U.USER_ID, U.NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소, CONCAT(LEFT(TLNO, 3), '-', MID(TLNO, 4, 4), '-', RIGHT(TLNO, 4)) AS 전화번호
FROM (SELECT DISTINCT WRITER_ID
      FROM USED_GOODS_BOARD
      GROUP BY WRITER_ID
      HAVING COUNT(WRITER_ID) >= 3) W LEFT JOIN USED_GOODS_USER U ON W.WRITER_ID = U.USER_ID
ORDER BY U.USER_ID DESC;