WITH AVG_SALARY AS (
    SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)
SELECT HD.DEPT_ID, HD.DEPT_NAME_EN, AVG_SALARY.AVG_SAL
FROM HR_DEPARTMENT HD
RIGHT JOIN AVG_SALARY
ON HD.DEPT_ID = AVG_SALARY.DEPT_ID
ORDER BY AVG_SALARY.AVG_SAL DESC;