WITH TRUNCATE_PRICE_TABLE AS (
    SELECT *, TRUNCATE(PRICE / 10000, 0) AS TRUNCATE_PRICE
    FROM PRODUCT
)
SELECT (TRUNCATE_PRICE * 10000) AS PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM TRUNCATE_PRICE_TABLE
GROUP BY TRUNCATE_PRICE
ORDER BY PRICE_GROUP;