SELECT VISITED_ON, AMOUNT, ROUND(AMOUNT / 7 , 2) AVERAGE_AMOUNT
FROM (
SELECT DISTINCT VISITED_ON,
    SUM(AMOUNT) OVER (ORDER BY VISITED_ON RANGE BETWEEN INTERVAL 6 DAY PRECEDING AND CURRENT ROW) AMOUNT,
    MIN(VISITED_ON) OVER() FIRST
FROM CUSTOMER
) C
WHERE VISITED_ON >= FIRST + 6;