WITH JAN_SALES AS (
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-01'
    GROUP BY BOOK_ID
)
SELECT BOOK.CATEGORY, SUM(JAN_SALES.TOTAL_SALES) AS TOTAL_SALES
FROM JAN_SALES
LEFT JOIN BOOK
ON JAN_SALES.BOOK_ID = BOOK.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY;