WITH CAR1 AS (
    SELECT CRCRH.HISTORY_ID, CRCRH.CAR_ID, CRCC.CAR_TYPE,
            CASE 
                WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 >= 7 THEN '7일 이상'
            END AS DURATION_TYPE,
            (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1) * DAILY_FEE AS TOTAL_FEE
    FROM CAR_RENTAL_COMPANY_CAR CRCC
    RIGHT JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
    ON CRCC.CAR_ID = CRCRH.CAR_ID
    WHERE CAR_TYPE = '트럭'
)
SELECT HISTORY_ID, 
        CASE 
            WHEN CRCDP.DISCOUNT_RATE IS NULL THEN CAR1.TOTAL_FEE
            ELSE CAR1.TOTAL_FEE * (100 - (TRIM(TRAILING '%' FROM CRCDP.DISCOUNT_RATE)))/100
        END AS FEE
FROM CAR1
LEFT JOIN
CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
ON (CAR1.CAR_TYPE = CRCDP.CAR_TYPE) AND CRCDP.DURATION_TYPE = CAR1.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;