-- 물고기 종류별 물고기 이름, 잡은 수
-- 잡은 수 내림차순

SELECT COUNT(*) AS FISH_COUNT, N.FISH_NAME
FROM FISH_INFO F
    JOIN FISH_NAME_INFO N ON F.FISH_TYPE = N.FISH_TYPE
GROUP BY
    N.FISH_NAME
ORDER BY FISH_COUNT DESC;