SELECT 
  CASE 
    WHEN (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) > 0 
         AND EXISTS (
           SELECT 1 FROM SKILLCODES 
           WHERE CATEGORY = 'Front End'
             AND (SKILL_CODE & CODE) > 0
         ) THEN 'A'
    WHEN (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) > 0 THEN 'B'
    WHEN EXISTS (
           SELECT 1 FROM SKILLCODES 
           WHERE CATEGORY = 'Front End'
             AND (SKILL_CODE & CODE) > 0
         ) THEN 'C'
  END AS GRADE, 
  ID, 
  EMAIL 
FROM DEVELOPERS
WHERE 
  ((SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) > 0 
   AND EXISTS (
     SELECT 1 FROM SKILLCODES 
     WHERE CATEGORY = 'Front End'
       AND (SKILL_CODE & CODE) > 0
   ))
  OR (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) > 0
  OR EXISTS (
    SELECT 1 FROM SKILLCODES 
    WHERE CATEGORY = 'Front End'
      AND (SKILL_CODE & CODE) > 0
  )
ORDER BY GRADE, ID;
