WITH TOP_BOARD AS (
    SELECT *
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) FILE_PATH
FROM TOP_BOARD TB
JOIN USED_GOODS_FILE UGF
ON TB.BOARD_ID = UGF.BOARD_ID
ORDER BY FILE_ID DESC;