WITH COUNT_TABLE AS (
    SELECT HOST_ID, COUNT(*) AS REGISTER_COUNT
    FROM PLACES
    GROUP BY HOST_ID
    HAVING REGISTER_COUNT >= 2
)
SELECT PLACES.ID, PLACES.NAME, PLACES.HOST_ID
FROM PLACES
RIGHT JOIN COUNT_TABLE
ON PLACES.HOST_ID = COUNT_TABLE.HOST_ID
ORDER BY ID;