WITH RANK_TABLE AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RNK
    FROM FOOD_PRODUCT
)
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM RANK_TABLE
WHERE CATEGORY IN ('과자', '국', '김치', '식용유') AND RNK = 1
ORDER BY MAX_PRICE DESC;