-- 테이블: 고객 정보, 식당 리뷰 정보
-- 리뷰 가장 많이 작성한 회원의 리뷰 조회
-- 작성일 오름, 리뷰 텍스트 오름

-- 윈도우 rank 가장 많이 작성한 회원 구하기
-- 리뷰에 회원정보 조인해서 이름 알아내기

WITH RANK_RESULT AS (
    SELECT MEMBER_ID, RANK() OVER (ORDER BY REVIEW_COUNT DESC) AS REVIEW_RANK
    FROM (
        SELECT MEMBER_ID, COUNT(*) REVIEW_COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) RESULT
)

SELECT M.MEMBER_NAME, RE.REVIEW_TEXT, DATE_FORMAT(RE.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW RE
JOIN RANK_RESULT RA ON RE.MEMBER_ID = RA.MEMBER_ID AND RA.REVIEW_RANK = 1
JOIN MEMBER_PROFILE M ON RE.MEMBER_ID = M.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;