WITH MAX_DATA AS( 
    SELECT MAX(SIZE_OF_COLONY) AS MAX, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR, (MD.MAX - ED.SIZE_OF_COLONY) AS YEAR_DEV, ED.ID
FROM ECOLI_DATA ED
LEFT JOIN MAX_DATA MD
ON YEAR(ED.DIFFERENTIATION_DATE) = MD.YEAR
ORDER BY YEAR, YEAR_DEV;
