SELECT DATE_FORMAT(o.sales_date, '%Y') AS YEAR, DATE_FORMAT(o.sales_date, '%m') AS MONTH, COUNT(DISTINCT o.user_id) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT o.user_id) / (SELECT COUNT(user_id) FROM USER_INFO WHERE joined like "2021%"),1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS o
JOIN USER_INFO AS u
ON u.user_id = o.user_id
WHERE u.joined like "2021%"
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;